### ISSUE TITLE
默认只搜索手办

### ISSUE THREAD

**Issue by tonzhou** [Nyarlathotep233/bilibili-magic-market-search#1]
可以更改搜索条目吗，会丢失一些搜索，比如fufu

**Comment by Nyarlathotep233** [comment]
可以试试看手动把 config.json 里 categoryFilter 的值改成空字符串或其它值（周边应该是 ”2331“）（或者拉下新的代码，新的代码默认是所有品类了）

**Comment by tonzhou** [comment]
> 可以尝试看手动把 config.json 里categoryFilter的值改成应该空字符串或其他值（周围是”2331“）（或者拉下新的代码，新的代码默认是所有品类了）

十分感谢，已经解决
