### ISSUE TITLE
找不到模块？小白不懂

### ISSUE THREAD

**Issue by CanotDrum** [Nyarlathotep233/bilibili-magic-market-search#3]
如图
![`9DP 5CR@{~703T16O57$7X](https://github.com/Nyarlathotep233/bilibili-magic-market-search/assets/91821202/7da9815c-5c77-44e7-9762-a2e6e6b6264d)

**Comment by Diolance** [comment]
初次需要先执行npm install吧

**Comment by CanotDrum** [comment]
感谢 成了
