### ISSUE TITLE
不能成功输出结果是什么情况？

### ISSUE THREAD

**Issue by kuebe1** [Nyarlathotep233/bilibili-magic-market-search#4]
用过一会可以正常输出list文件，里面为想要的数据，但是突然间输出不了了，程序还可以正常运行，list文件也能生成，但一直为空

**Comment by Nyarlathotep233** [comment]
是换过关键词后希望重新搜索吗？试试看把根目录下的 nextId.txt 删掉试试？终端中有输出报错吗？

**Comment by kuebe1** [comment]
> 是换过关键词后希望重新搜索吗？试试看把根目录下的 nextId.txt 删掉试试？终端中有输出报错吗？

我每次搜索都会删掉nextld和list，输出报错没有，过程正常。还有就是我发现不是什么都不输出，而是会少很多结果，我扩大搜索范围后能搜到一些，会不会和b站的cookie有关？我需要重新复制一遍cookie吗？

**Comment by Nyarlathotep233** [comment]
> > 是换过关键词后希望重新搜索吗？试试看把根目录下的 nextId.txt 删掉试试？终端中有输出报错吗？
> 
> 我每次搜索都会删掉nextld和list，输出报错没有，过程正常。还有就是我发现不是什么都不输出，而是会少很多结果，我扩大搜索范围后能搜到一些，会不会和b站的cookie有关？我需要重新复制一遍cookie吗？

我也不是很了解b站市集给用户推送的机制，照理来说cookie只要没过期，还能请求到东西应该就不需要重新复制一遍cookie。
你或者可以试试换个账号，来看看是不是b站针对不同账号推送的内容不一样？
或者也有可能只是单纯商品被卖出去了。😂

**Comment by kuebe1** [comment]
> 是换过关键词后希望重新搜索吗？试试看把根目录下的 nextId.txt 删掉试试？终端中有输出报错吗？

我每次搜索都会删掉nextld和list，输出报错没有，过程正常。还有就是我发现不是什么都不输出，而是会少很多结果，我扩大搜索范围后能搜到一些，会不会和b站的cookie有关？我需要重新复制一遍cookie吗？

> > > 是换过关键词后希望重新搜索吗？试试看把根目录下的 nextId.txt 删掉试试？终端中有输出报错吗？
> > 
> > 
> > 我每次搜索都会删掉nextld和list，输出报错没有，过程正常。还有就是我发现不是什么都不输出，而是会少很多结果，我扩大搜索范围后能搜到一些，会不会和b站的cookie有关？我需要重新复制一遍cookie吗？
> 
> 我也不是很了解b站市集给用户推送的机制，照理来说cookie只要没过期，还能请求到东西应该就不需要重新复制一遍cookie。 你或者可以试试换个账号，来看看是不是b站针对不同账号推送的内容不一样？ 或者也有可能只是单纯商品被卖出去了。😂

我自己手动刷都还能刷到，应该还没卖出去，我又试了试，2312搜手办时好像能正常无误，2331搜周边时就会有遗漏

**Comment by Nyarlathotep233** [comment]
> > 是换过关键词后希望重新搜索吗？试试看把根目录下的 nextId.txt 删掉试试？终端中有输出报错吗？
> 
> 我每次搜索都会删掉nextld和list，输出报错没有，过程正常。还有就是我发现不是什么都不输出，而是会少很多结果，我扩大搜索范围后能搜到一些，会不会和b站的cookie有关？我需要重新复制一遍cookie吗？
> 
> > > > 是换过关键词后希望重新搜索吗？试试看把根目录下的 nextId.txt 删掉试试？终端中有输出报错吗？
> > > 
> > > 
> > > 我每次搜索都会删掉nextld和list，输出报错没有，过程正常。还有就是我发现不是什么都不输出，而是会少很多结果，我扩大搜索范围后能搜到一些，会不会和b站的cookie有关？我需要重新复制一遍cookie吗？
> > 
> > 我也不是很了解b站市集给用户推送的机制，照理来说cookie只要没过期，还能请求到东西应该就不需要重新复制一遍cookie。 你或者可以试试换个账号，来看看是不是b站针对不同账号推送的内容不一样？ 或者也有可能只是单纯商品被卖出去了。😂
> 
> 我自己手动刷都还能刷到，应该还没卖出去，我又试了试，2312搜手办时好像能正常无误，2331搜周边时就会有遗漏

你能发我下请求时用的参数吗，可以发我邮箱里: 809679663@qq.com
