### ISSUE TITLE
不往list.json里写东西

### ISSUE THREAD

**Issue by floathua** [Nyarlathotep233/bilibili-magic-market-search#5]
每跑一行都不往里面写东西
<img width="1088" alt="AFE3E49D0C4210B2827B25E09AC67D9A" src="https://github.com/Nyarlathotep233/bilibili-magic-market-search/assets/86044708/984bcce0-dcc0-4d1d-83dc-f8f05c30fd68">
<img width="720" alt="C4FE2B7B46FB37DB718D79BA8ED60C0E" src="https://github.com/Nyarlathotep233/bilibili-magic-market-search/assets/86044708/db0495f8-9a8e-4d0f-a65a-15ff5ee23647">

**Comment by Nyarlathotep233** [comment]
现在的逻辑是必须满足name里的所有条件，才会存下来，你试试去掉“毛绒玩偶”后再搜搜看有没有东西
